# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindowLoginByFaceID.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowLoginByFaceID(object):
    def setupUi(self, MainWindowLoginByFaceID):
        MainWindowLoginByFaceID.setObjectName("MainWindowLoginByFaceID")
        MainWindowLoginByFaceID.resize(640, 497)
        self.centralwidget = QtWidgets.QWidget(MainWindowLoginByFaceID)
        self.centralwidget.setObjectName("centralwidget")
        self.lbImg = QtWidgets.QLabel(self.centralwidget)
        self.lbImg.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.lbImg.setText("")
        self.lbImg.setPixmap(QtGui.QPixmap("Logo/imgNone.png"))
        self.lbImg.setObjectName("lbImg")
        MainWindowLoginByFaceID.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowLoginByFaceID)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindowLoginByFaceID.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowLoginByFaceID)
        self.statusbar.setObjectName("statusbar")
        MainWindowLoginByFaceID.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowLoginByFaceID)
        QtCore.QMetaObject.connectSlotsByName(MainWindowLoginByFaceID)

    def retranslateUi(self, MainWindowLoginByFaceID):
        _translate = QtCore.QCoreApplication.translate
        MainWindowLoginByFaceID.setWindowTitle(_translate("MainWindowLoginByFaceID", "Face Recognition version 1.0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowLoginByFaceID = QtWidgets.QMainWindow()
    ui = Ui_MainWindowLoginByFaceID()
    ui.setupUi(MainWindowLoginByFaceID)
    MainWindowLoginByFaceID.show()
    sys.exit(app.exec_())
